name: Update test snapshots
on: 
  workflow_dispatch:
  push:

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout the latest commit in this branch
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/workflows/actions/build-core

  test-core-screenshot:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/update-snapshots
      - uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'test: update visual snapshots'